Switch default mount point from /lib/live/mount/medium to /run/live/medium
In commit 0d878d3a679 of live-boot(-grml)
("Simplify mount point handling by using /run/live instead of /lib/live/mount")
the mountpath of /lib/live/mount/medium was moved towards /run/live/medium.

Commit c6a17c7b41b of live-boot(-grml) provides a backward compatibility
rbind mount, but occasionally there seems to be a regression somewhere
during boot (see https://github.com/grml/live-boot-grml/issues/10), and
the rbind mount will be deprecated and removed before the bullseye
(Debian 11) release.

Layout changes over time:

* /cdrom: old linuxrc approach
* /live/image for initramfs layout until December 2012
* /lib/live/mount/medium for initramfs layout since December 2012
* /run/live/medium for initramfs layout since December 2018

Drop support for everything but /run/live/medium and
/lib/live/mount/medium, while at it.

Also noticed that save-config wasn't properly handling the location of
the rootfs and overlay mount points, adjusted while at it.

Closes: grml/live-boot-grml#10

diff --git a/bin/save-config b/bin/save-config
--- a/bin/save-config
+++ b/bin/save-config
@@ -18,21 +18,22 @@
   LC_ALL=C
   [[ $UID != 0 ]] && runas='sudo' # important for /etc
 
-  if [ -d /lib/live/mount/overlay ] ; then # since around December 2012
-    CHANGE_DIR='/lib/live/mount/overlay'
-  elif [ -d /live/overlay ] ; then  # until around December 2012
-    CHANGE_DIR='/live/overlay'
-  elif [ -d /live/image ] ; then # old version
-    CHANGE_DIR='/live/image'
+  if [ -d /run/live/overlay/rw ] ; then # since Dec 2018
+    CHANGE_DIR='/run/live/overlay/rw'
+  elif [ -d /lib/live/mount/overlay/rw ] ; then # 2012 until Dec 2018, backwards compatibility
+    CHANGE_DIR='/lib/live/mount/overlay/rw'
   else
     echo "Error: no overlay directories found (like /lib/live/mount/overlay or /live/overlay)." >&2
     bailout; exit 1
   fi
 
-  if [ -d /live/rofs ] ; then
-    ORIG_DIR="$(find /live/rofs/ -maxdepth 1 -name \*.squashfs | head -1)"
-  else # old version
-    ORIG_DIR="/GRML"
+  if [ -d /run/live/rootfs ] ; then
+    ORIG_DIR="$(find /run/live/rootfs/ -maxdepth 1 -name \*.squashfs | head -1)"
+  elif [ -d /lib/live/mount/rootfs ] ; then
+    ORIG_DIR="$(find /lib/live/mount/rootfs/ -maxdepth 1 -name \*.squashfs | head -1)"
+  else
+    echo "Error: no rootfs directories found in '/run/live/rootfs' or '/lib/live/mount/rootfs'." >&2
+    bailout; exit 1
   fi
 
   check4progs mutt &>/dev/null || echo "Warning, mutt not available for mail handling.">&2
