grml-live: stop manipulating CWD

diff --git a/grml-live b/grml-live
--- a/grml-live
+++ b/grml-live
@@ -1635,50 +1635,45 @@ else
        ;;
    esac
 
-   if pushd "$BUILD_OUTPUT" >/dev/null; then
-      log   "Generating build information in conf/buildinfo.json"
-      einfo "Generating build information in conf/buildinfo.json"
-      mkdir -p conf/
-      generate_build_info > conf/buildinfo.json
-      eend $?
+   log   "Generating build information in conf/buildinfo.json"
+   einfo "Generating build information in conf/buildinfo.json"
+   mkdir -p "$BUILD_OUTPUT"/conf/
+   generate_build_info > "$BUILD_OUTPUT"/conf/buildinfo.json
+   eend $?
 
-      log "$MKISOFS -V '${GRML_NAME} ${VERSION}' -publisher 'grml-live | grml.org' -l -r -J $BOOT_ARGS $EFI_ARGS -no-pad -o ${ISO_OUTPUT}/${ISO_NAME} ."
-      einfo "Generating ISO file..."
-      # shellcheck disable=SC2086 # BOOT_ARGS and EFI_ARGS need splitting
-      $MKISOFS -V "${GRML_NAME} ${VERSION}" -publisher 'grml-live | grml.org' \
-              -l -r -J $BOOT_ARGS $EFI_ARGS -no-pad \
-              -o "${ISO_OUTPUT}/${ISO_NAME}" . ; RC=$?
-      eend $RC
+   log "$MKISOFS -V '${GRML_NAME} ${VERSION}' -publisher 'grml-live | grml.org' -l -r -J $BOOT_ARGS $EFI_ARGS -no-pad -o ${ISO_OUTPUT}/${ISO_NAME} ."
+   einfo "Generating ISO file..."
+   # shellcheck disable=SC2086 # BOOT_ARGS and EFI_ARGS need splitting
+   $MKISOFS -V "${GRML_NAME} ${VERSION}" -publisher 'grml-live | grml.org' \
+           -l -r -J $BOOT_ARGS $EFI_ARGS -no-pad \
+           -o "${ISO_OUTPUT}/${ISO_NAME}" "$BUILD_OUTPUT"/ ; RC=$?
+   eend $RC
 
-      # do not continue on errors, otherwise we might generate/overwrite the ISO with dd if=... stuff
-      if [ "$RC" != 0 ] ; then
-        log    "Error: critical error while generating ISO [exit code ${RC}]. Exiting."
-        eerror "Error: critical error while generating ISO [exit code ${RC}]. Exiting." ; eend 1
-        bailout "$RC"
-      fi
-
-      # pad the output ISO to multiples of 256 KiB for partition table support
-      siz=$($getfilesize "${ISO_OUTPUT}/${ISO_NAME}")
-      cyls=$((siz / 512 / 32 / 16 + 1))   # C=$cyls H=16 S=32
-      siz=$((cyls * 16 * 32 * 512))   # size after padding
-      dd if=/dev/zero bs=1 count=1 seek=$((siz - 1)) \
-         of="${ISO_OUTPUT}/${ISO_NAME}" 2>/dev/null
-
-      # generate ISO checksums if we are using class 'RELEASE':
-      case $CLASSES in *RELEASE*)
-         [ "$RC" = 0 ] && \
-         (
-           if cd "$ISO_OUTPUT" ; then
-             sha256sum "${ISO_NAME}" > "${ISO_NAME}.sha256" && \
-             touch -r "${ISO_NAME}" "${ISO_NAME}.sha256"
-           fi
-         )
-         ;;
-      esac
-
-      # shellcheck disable=SC2164 # If previous CWD disappears, what are we gonna do.
-      popd >/dev/null
+   # do not continue on errors, otherwise we might generate/overwrite the ISO with dd if=... stuff
+   if [ "$RC" != 0 ] ; then
+     log    "Error: critical error while generating ISO [exit code ${RC}]. Exiting."
+     eerror "Error: critical error while generating ISO [exit code ${RC}]. Exiting." ; eend 1
+     bailout "$RC"
    fi
+
+   # pad the output ISO to multiples of 256 KiB for partition table support
+   siz=$($getfilesize "${ISO_OUTPUT}/${ISO_NAME}")
+   cyls=$((siz / 512 / 32 / 16 + 1))   # C=$cyls H=16 S=32
+   siz=$((cyls * 16 * 32 * 512))   # size after padding
+   dd if=/dev/zero bs=1 count=1 seek=$((siz - 1)) \
+      of="${ISO_OUTPUT}/${ISO_NAME}" 2>/dev/null
+
+   # generate ISO checksums if we are using class 'RELEASE':
+   case $CLASSES in *RELEASE*)
+      [ "$RC" = 0 ] && \
+      (
+        if cd "$ISO_OUTPUT" ; then
+          sha256sum "${ISO_NAME}" > "${ISO_NAME}.sha256" && \
+          touch -r "${ISO_NAME}" "${ISO_NAME}.sha256"
+        fi
+      )
+      ;;
+   esac
 
    if [ "$RC" = 0 ] ; then
       log   "Finished execution of stage 'iso build' [$(date)]"
