grml-live: unindent if false blocks
And rework check for chroot existence.

diff --git a/grml-live b/grml-live
--- a/grml-live
+++ b/grml-live
@@ -714,77 +714,66 @@ if [ -z "$BOOTSTRAP_MIRROR" ] ; then
 fi
 # }}}
 
-# CHROOT_OUTPUT - execute FAI {{{
-if false ; then
-   log   "Skipping stage 'fai' as requested via option -B"
-   ewarn "Skipping stage 'fai' as requested via option -B" ; eend 0
+# execute minifai {{{
+if [ -n "$BOOTSTRAP_ONLY" ] ; then
+  FAI_ACTION=bootstrap
+elif [ -n "$BUILD_ONLY" ] ; then
+  FAI_ACTION=reconfigure
+elif [ -n "$UPDATE" ] ; then
+  FAI_ACTION=softupdate
+elif [ -n "$BUILD_DIRTY" ] ; then
+  FAI_ACTION=rebuild
+elif [ -d "$CHROOT_OUTPUT/etc/debian_version" ] ; then
+  log   "Skipping chroot bootstrap as $CHROOT_OUTPUT exists already."
+  ewarn "Skipping chroot bootstrap as $CHROOT_OUTPUT exists already." ; eend 0
+  FAI_ACTION=rebuild
 else
-   if [ -n "$BOOTSTRAP_ONLY" ] ; then
-      FAI_ACTION=bootstrap
-   elif [ -n "$BUILD_ONLY" ] ; then
-      FAI_ACTION=reconfigure
-   elif [ -n "$UPDATE" ] ; then
-      FAI_ACTION=softupdate
-   elif [ -n "$BUILD_DIRTY" ] ; then
-      FAI_ACTION=rebuild
-   elif [ -d "$CHROOT_OUTPUT/bin" ] ; then
-      log   "Skipping chroot bootstrap as $CHROOT_OUTPUT exists already."
-      ewarn "Skipping chroot bootstrap as $CHROOT_OUTPUT exists already." ; eend 0
-   else
-      FAI_ACTION=dirinstall
-   fi
+  FAI_ACTION=dirinstall
+fi
 
-   if [ -n "$UPDATE" ] || [ -n "$BUILD_ONLY" ] || [ -n "$BUILD_DIRTY" ] ; then
-      if ! [ -r "$CHROOT_OUTPUT/etc/debian_version" ] ; then
-         log    "Error: does not look like you have a working chroot. Updating/building not possible."
-         eerror "Error: does not look like you have a working chroot. Updating/building not possible. (Drop -u/-b/-B option?)"
-         eend 1
-         bailout 20
-      fi
-   fi
+if ! [ "$FAI_ACTION" = dirinstall ] && ! [ -r "$CHROOT_OUTPUT/etc/debian_version" ] ; then
+  log    "Error: does not look like you have a working chroot. Updating/building not possible."
+  eerror "Error: does not look like you have a working chroot. Updating/building not possible. (Drop -u/-b/-B option?)"
+  eend 1
+  bailout 20
+fi
 
-   if false ; then
-      log   "Skipping stage 'fai $FAI_ACTION' as $CHROOT_OUTPUT exists already."
-      ewarn "Skipping stage 'fai $FAI_ACTION' as $CHROOT_OUTPUT exists already." ; eend 0
-   else
-      mkdir -p "$CHROOT_OUTPUT" || bailout 5 "Problem with creating $CHROOT_OUTPUT for FAI"
+mkdir -p "$CHROOT_OUTPUT" || bailout 5 "Problem with creating $CHROOT_OUTPUT"
 
-      if [ -n "${MIRROR_DIRECTORY}" ] ; then
-         mkdir -p "${CHROOT_OUTPUT}/${MIRROR_DIRECTORY}"
-         mount --bind "${MIRROR_DIRECTORY}" "${CHROOT_OUTPUT}/${MIRROR_DIRECTORY}"
-      fi
+if [ -n "${MIRROR_DIRECTORY}" ] ; then
+  mkdir -p "${CHROOT_OUTPUT}/${MIRROR_DIRECTORY}"
+  mount --bind "${MIRROR_DIRECTORY}" "${CHROOT_OUTPUT}/${MIRROR_DIRECTORY}"
+fi
 
-      log "Executed FAI command line:"
-      log "${FAI_PROGRAM} ${GRML_FAI_CONFIG} ${CLASSES} ${FAI_ACTION} ${CHROOT_OUTPUT} ${CONFIGDUMP} ${SUITE} ${BOOTSTRAP_MIRROR}"
-      einfo "${FAI_PROGRAM} ${GRML_FAI_CONFIG} ${CLASSES} ${FAI_ACTION} ${CHROOT_OUTPUT} ${CONFIGDUMP} ${SUITE} ${BOOTSTRAP_MIRROR}"
-      "${FAI_PROGRAM}" "${GRML_FAI_CONFIG}" "${CLASSES}" "${FAI_ACTION}" "${CHROOT_OUTPUT}" "${CONFIGDUMP}" "${SUITE}" "${BOOTSTRAP_MIRROR}" 2>&1 | tee -a "${LOGFILE}"
-      RC="${PIPESTATUS[0]}" # notice: bash-only
+log "Executed FAI command line:"
+log "${FAI_PROGRAM} ${GRML_FAI_CONFIG} ${CLASSES} ${FAI_ACTION} ${CHROOT_OUTPUT} ${CONFIGDUMP} ${SUITE} ${BOOTSTRAP_MIRROR}"
+einfo "${FAI_PROGRAM} ${GRML_FAI_CONFIG} ${CLASSES} ${FAI_ACTION} ${CHROOT_OUTPUT} ${CONFIGDUMP} ${SUITE} ${BOOTSTRAP_MIRROR}"
+"${FAI_PROGRAM}" "${GRML_FAI_CONFIG}" "${CLASSES}" "${FAI_ACTION}" "${CHROOT_OUTPUT}" "${CONFIGDUMP}" "${SUITE}" "${BOOTSTRAP_MIRROR}" 2>&1 | tee -a "${LOGFILE}"
+RC="${PIPESTATUS[0]}" # notice: bash-only
 
-      # Fetches logs from "${CHROOT_OUTPUT}"/grml-live/log.
-      # Also run this on failure.
-      store_logfiles
+# Fetches logs from "${CHROOT_OUTPUT}"/grml-live/log.
+# Also run this on failure.
+store_logfiles
 
-      if [ "$RC" != 0 ] ; then
-        log    "Error: critical error while executing fai [exit code ${RC}]. Exiting."
-        eerror "Error: critical error while executing fai [exit code ${RC}]. Exiting." ; eend 1
-        bailout 1
-      fi
+if [ "$RC" != 0 ] ; then
+  log    "Error: critical error while executing fai [exit code ${RC}]. Exiting."
+  eerror "Error: critical error while executing fai [exit code ${RC}]. Exiting." ; eend 1
+  bailout 1
+fi
 
-      mv "${CHROOT_OUTPUT}"/grml-live/grml_sources/ "${OUTPUT}"
+mv "${CHROOT_OUTPUT}"/grml-live/grml_sources/ "${OUTPUT}"
 
-      # provide inform fai about the ISO we build, needs to be provided
-      # *after* FAI stage, otherwise FAI skips the debootstrap stage if
-      # there is not BASEFILE (as it checks for presence of /etc) :(
-      echo '# This file has been generated by grml-live.' > "$CHROOT_OUTPUT/etc/grml_live_version"
-      [ -n "$GRML_LIVE_VERSION" ] && echo "GRML_LIVE_VERSION=$GRML_LIVE_VERSION" >> "$CHROOT_OUTPUT/etc/grml_live_version"
-      [ -n "$SUITE" ] && echo "SUITE=$SUITE" >> "$CHROOT_OUTPUT/etc/grml_live_version"
+# provide inform fai about the ISO we build, needs to be provided
+# *after* FAI stage, otherwise FAI skips the debootstrap stage if
+# there is not BASEFILE (as it checks for presence of /etc) :(
+echo '# This file has been generated by grml-live.' > "$CHROOT_OUTPUT/etc/grml_live_version"
+[ -n "$GRML_LIVE_VERSION" ] && echo "GRML_LIVE_VERSION=$GRML_LIVE_VERSION" >> "$CHROOT_OUTPUT/etc/grml_live_version"
+[ -n "$SUITE" ] && echo "SUITE=$SUITE" >> "$CHROOT_OUTPUT/etc/grml_live_version"
 
-      umount_all
+umount_all
 
-      log "Finished execution of stage 'fai $FAI_ACTION' [$(date)]"
-      einfo "Finished execution of stage 'fai $FAI_ACTION'"
-   fi
-fi # BUILD_DIRTY?
+log "Finished execution of stage 'fai $FAI_ACTION' [$(date)]"
+einfo "Finished execution of stage 'fai $FAI_ACTION'"
 # }}}
 
 # BUILD_OUTPUT - execute arch specific stuff and squashfs {{{
