grml-live: prevent running as root

diff --git a/grml-live b/grml-live
--- a/grml-live
+++ b/grml-live
@@ -89,23 +89,20 @@ More details: man grml-live + /usr/share/doc/grml-live/grml-live.html
 
 Please send your bug reports and feedback to the grml-team: http://grml.org/bugs/
 "
-   [ "$(id -u 2>/dev/null)" != 0 ] && echo "Please notice that this script requires root permissions."
 }
 
-# make sure it's possible to get usage information without being
-# root or actually executing the script
 if [ "$1" = '-h' ] || [ "$1" = '--help' ] ; then
    usage
    exit 0
 fi
 # }}}
 
-# some runtime checks {{{
-# we need root permissions for the build-process:
-if [ "$(id -u 2>/dev/null)" != 0 ] ; then
-   echo "Error: please run this script with uid 0 (root)." >&2
+# prevent running as root {{{
+if [ "$(id -u 2>/dev/null)" = 0 ] ; then
+   echo "Error: grml-live needs to run as non-root with working user namespaces." >&2
    exit 1
 fi
+# }}}
 
 # lsb-functions and configuration stuff {{{
 # make sure they are not set by default
