Fix stderr redirection in "/usr/sbin/fai already running..."

diff --git a/grml-live b/grml-live
--- a/grml-live
+++ b/grml-live
@@ -4,7 +4,7 @@
 # Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
 # Bug-Reports:   see http://grml.org/bugs/
 # License:       This file is licensed under the GPL v2 or any later version.
-# Latest change: Mit Okt 10 09:38:42 CEST 2007 [mika]
+# Latest change: Wed Oct 17 22:59:03 CEST 2007 [mika]
 ################################################################################
 
 # read configuration files, set some misc variables {{{
@@ -22,7 +22,7 @@ if [ "$(id -u 2>/dev/null)" != 0 ] ; then
 fi
 
 if [ -r /var/run/fai/FAI_INSTALLATION_IN_PROGRESS ] ; then
-   echo "/usr/sbin/fai already running or was aborted before."&>2
+   echo "/usr/sbin/fai already running or was aborted before.">&2
    echo "You may remove /var/run/fai/FAI_INSTALLATION_IN_PROGRESS and try again.">&2
    exit 1
 fi
