Support mksquashfs-lzma and $MKSQUASHFS in remaster/grml-live-remaster

diff --git a/remaster/grml-live-remaster b/remaster/grml-live-remaster
--- a/remaster/grml-live-remaster
+++ b/remaster/grml-live-remaster
@@ -30,7 +30,19 @@ GRML_LIVE_EDITOR=${VISUAL:-${EDITOR:-vi}}
 # }}}
 
 # make sure we have what we need {{{
-check4progs mkisofs mksquashfs stat || exit 1
+check4progs mkisofs stat || exit 1
+
+# allow overriding via environment:
+if [ -z "$MKSQUASHFS" ] ; then
+  if which mksquashfs-lzma >/dev/null 2>&1 ; then
+    MKSQUASHFS=mksquashfs-lzma
+  elif which mksquashfs >/dev/null 2>&1 ; then
+    MKSQUASHFS=mksquashfs
+  else
+    echo "Error: neither mksquashfs-lzma nor mksquashfs present. Exiting."
+    exit 1
+  fi
+fi
 check4root || exit 1
 # }}}
 
@@ -107,7 +119,7 @@ sed 3,4d "${BOOTSTUFF}"/boot.msg \
 sed 1,2d /remaster/msg >>/remaster/iso/boot/isolinux/boot.msg
 
 mkdir /remaster/iso/live
-mksquashfs /remaster/chroot /remaster/iso/live/"$(basename $SQUASHFS_FILE)"
+$MKSQUASHFS /remaster/chroot /remaster/iso/live/"$(basename $SQUASHFS_FILE)"
 umount /remaster/chroot /remaster/cdrom
 
 if [ -f /remaster/iso/boot/isolinux/isolinux.bin ] ; then
