Package validation: also detect packages that failed to install
So far we detected only packages that have been requested for
installation but failed because the package isn't *available*
(as in not available in the configured Debian repositories).

Without checking for packages that have been requested for
installation but failed because of dependency issues we
might be left in a state with missing packages.

So let's check for both situations and generate according JUnit
reports.

diff --git a/etc/grml/fai/config/scripts/GRMLBASE/01-packages b/etc/grml/fai/config/scripts/GRMLBASE/01-packages
--- a/etc/grml/fai/config/scripts/GRMLBASE/01-packages
+++ b/etc/grml/fai/config/scripts/GRMLBASE/01-packages
@@ -15,11 +15,22 @@ if ! [ -r "$target/${PACKAGE_LIST}" ] ; then
    echo "No $target/${PACKAGE_LIST} found, will not run package validation check."
 else
    printf "Validating package list: "
-   if $ROOTCMD dpkg --list $(grep -v '^#' $target/${PACKAGE_LIST} | grep -v -- '-$') >/dev/null 2>$LOGDIR/package_errors.log ; then
-      printf "done - no errors found\n"
-   else
+   TMPFILE=$(mktemp)
+
+   $ROOTCMD dpkg --list $(grep -v '^#' $target/${PACKAGE_LIST} | grep -v -- '-$') 2>&1 | \
+     grep -e '^un' -e 'No packages' > "$TMPFILE" || true
+
+   awk '/^un/ {print $2 " not_installable"}' "$TMPFILE" > "$LOGDIR/package_errors.log"
+   awk '/^No packages found matching/ {print $5 " not_available"}' "$TMPFILE" | \
+     sed 's/\. / /' >> "$LOGDIR/package_errors.log"
+
+   if [ -s "$TMPFILE" ] ; then
       printf "failed (there have been errors, find them at $LOGDIR/package_errors.log)\n"
+   else
+      printf "done - no errors found\n"
    fi
+
+   rm -f "$TMPFILE"
 fi
 
 ## END OF FILE #################################################################
