Provide workaround for systemd's systemctl failures on jessie
For unknown reasons `systemctl preset-all` and
`systemctl set-default grml-boot.target` return with exit code 1
even though it seems to be working fine.

diff --git a/etc/grml/fai/config/scripts/GRMLBASE/15-initsetup b/etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
--- a/etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
+++ b/etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
@@ -16,8 +16,17 @@ systemd_setup() {
   echo "Enabling user '$USERNAME' for autologin"
   sed -i "s/\$USERNAME/$USERNAME/" "$target"/etc/systemd/system/getty@tty*.service.d/override.conf
 
-  $ROOTCMD systemctl preset-all
-  $ROOTCMD systemctl set-default grml-boot.target
+  case "$(cat "${target}"/etc/debian_version)" in
+    8.*)
+      echo "Debian jessie detected. Enabling workaround for unknown systemctl preset-all/set-default exit failure."
+      $ROOTCMD systemctl preset-all || true
+      $ROOTCMD systemctl set-default grml-boot.target || true
+      ;;
+    *)
+      $ROOTCMD systemctl preset-all
+      $ROOTCMD systemctl set-default grml-boot.target
+      ;;
+  esac
 }
 
 file_rc_setup() {
