94-update-smart-drivedb: do not fail on update-smart-drivedb errors
Currently the
http://sourceforge.net/p/smartmontools/code/HEAD/tree/trunk/smartmontools/drivedb.h?format=raw
and related files on sourceforge aren't available and therefor
cause our builds to fail with:

| Updating smartmontool drivedb
| /usr/sbin/update-smart-drivedb: download from trunk failed (HTTP error)

Therefore don't break our builds but instead log a warning
message instead.

diff --git a/etc/grml/fai/config/scripts/GRMLBASE/94-update-smart-drivedb b/etc/grml/fai/config/scripts/GRMLBASE/94-update-smart-drivedb
--- a/etc/grml/fai/config/scripts/GRMLBASE/94-update-smart-drivedb
+++ b/etc/grml/fai/config/scripts/GRMLBASE/94-update-smart-drivedb
@@ -23,9 +23,13 @@ fi
 
 echo "Updating smartmontool drivedb"
 if [ -n "$TIMEOUT" ] ; then
-   $ROOTCMD timeout $TIMEOUT update-smart-drivedb
+   if ! $ROOTCMD timeout $TIMEOUT update-smart-drivedb ; then
+     echo "Warning: failed to update smartmontool drivedb, ignoring failure"
+   fi
 else
-   $ROOTCMD update-smart-drivedb
+   if ! $ROOTCMD update-smart-drivedb ; then
+     echo "Warning: failed to update smartmontool drivedb, ignoring failure"
+   fi
 fi
 
 ## END OF FILE #################################################################
