Adjust 95-package-information for new log layout

diff --git a/etc/grml/fai/config/scripts/GRMLBASE/95-package-information b/etc/grml/fai/config/scripts/GRMLBASE/95-package-information
--- a/etc/grml/fai/config/scripts/GRMLBASE/95-package-information
+++ b/etc/grml/fai/config/scripts/GRMLBASE/95-package-information
@@ -11,12 +11,17 @@ HOSTNAME=''
 [ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
 [ -n "$HOSTNAME" ] || HOSTNAME=grml
 
-if [ -x $target/usr/bin/dpkg-query ] ; then
-   $ROOTCMD dpkg-query -W --showformat='${Package}\t${Installed-Size;10}\n' > \
-   /var/log/fai/dirinstall/$HOSTNAME/packages.size
+if ! [ -d /var/log/fai/"$HOSTNAME"/last/ ] ; then
+   echo "Error: /var/log/fai/"$HOSTNAME"/last/ not available. Exiting.">&2
+   exit 1
 fi
 
-COLUMNS=200 $ROOTCMD dpkg --list > /var/log/fai/dirinstall/$HOSTNAME/dpkg.list
-COLUMNS=200 $ROOTCMD dpkg --get-selections > /var/log/fai/dirinstall/$HOSTNAME/dpkg.selections
+if [ -x $target/usr/bin/dpkg-query ] ; then
+   $ROOTCMD dpkg-query -W --showformat='${Package}\t${Installed-Size;10}\n' > \
+   /var/log/fai/$HOSTNAME/last/packages.size
+fi
+
+COLUMNS=200 $ROOTCMD dpkg --list > /var/log/fai/$HOSTNAME/last/dpkg.list
+COLUMNS=200 $ROOTCMD dpkg --get-selections > /var/log/fai/$HOSTNAME/last/dpkg.selections
 
 ## END OF FILE #################################################################
