Improve check for presence of FAI log directory

diff --git a/etc/grml/fai/config/scripts/GRMLBASE/95-package-information b/etc/grml/fai/config/scripts/GRMLBASE/95-package-information
--- a/etc/grml/fai/config/scripts/GRMLBASE/95-package-information
+++ b/etc/grml/fai/config/scripts/GRMLBASE/95-package-information
@@ -4,7 +4,7 @@
 # Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
 # Bug-Reports:   see http://grml.org/bugs/
 # License:       This file is licensed under the GPL v2 or any later version.
-# Latest change: Sun Dec 16 16:23:04 CET 2007 [mika]
+# Latest change: Mon Dec 17 00:54:41 CET 2007 [mika]
 ################################################################################
 
 HOSTNAME=''
@@ -12,8 +12,8 @@ HOSTNAME=''
 [ -r /etc/grml/grml-live.local ] && . /etc/grml/grml-live.local
 [ -n "$HOSTNAME" ] || HOSTNAME=grml
 
-if ! [ -d /var/log/fai/"$HOSTNAME"/last/ ] ; then
-   echo "Error: /var/log/fai/"$HOSTNAME"/last/ not available. Exiting.">&2
+if ! [ -w /var/log/fai/"$HOSTNAME"/last/ ] ; then
+   echo "Error: can not write to /var/log/fai/"$HOSTNAME"/last/. Exiting.">&2
    exit 1
 fi
 
