Rework resolv.conf handling, error out on wrong symlinks. [Closes: issue984]
Make sure the resolv.conf setup is correct and error out
accordingly otherwise, while at it make sure the code
is the same in instsoft.GRMLBASE and 96-apt-listbugs.

Thanks to Andreas Korsten for reporting.

diff --git a/etc/grml/fai/config/scripts/GRMLBASE/96-apt-listbugs b/etc/grml/fai/config/scripts/GRMLBASE/96-apt-listbugs
--- a/etc/grml/fai/config/scripts/GRMLBASE/96-apt-listbugs
+++ b/etc/grml/fai/config/scripts/GRMLBASE/96-apt-listbugs
@@ -22,11 +22,24 @@ if ifclass RELEASE ; then
   [ -n "$HOSTNAME" ] || HOSTNAME=grml
 
   if [ -r /etc/resolv.conf ] ; then
-     if [ -d $target/etc/resolvconf/run ] ; then
+    if [ -d $target/etc/resolvconf/run ] ; then # resolvconf
+      # sanity check to avoid "input file is output file",
+      # see http://bts.grml.org/grml/issue984
+      if ! [ -L $target/etc/resolvconf/run/resolv.conf ] ; then
         cat /etc/resolv.conf >> $target/etc/resolvconf/run/resolv.conf
-     elif [ ! -L $target/etc/resolv.conf ] ; then
+      else
+        echo "Error: /etc/resolvconf/run/resolv.conf in chroot should not be a symlink." >&2
+        echo "       Looks like something is wrong, please fix manually." >&2
+        exit 1
+      fi
+    else # no resolvconf installed in chroot
+      if ! [ -L $target/etc/resolv.conf ] ; then
         cat /etc/resolv.conf >> $target/etc/resolv.conf
-     fi
+      else
+        echo "Error: /etc/resolv.conf in chroot should not be a symlink (resolvconf not installed)." >&2
+        exit 1
+      fi
+    fi
   fi
 
   if [ -x $target/usr/sbin/apt-listbugs -a -x $target/usr/bin/apt-show-source ] && \
